posts/urls.py
from django.urls import path
from .views import main_post_view, liked_unliked_view, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('',main_post_view, name='main-post-view'),
    path('liked/',liked_unliked_view, name='liked-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view, 
    my_invites_view, 
    AllProfilesView,
    send_invatation, 
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    ProfileDetailView,
)

app_name = 'profiles'

urlpatterns = [
    path('my-profile/', my_profile_view, name='my-profile'),
    path('my-invites/', my_invites_view, name='my-invites'),
    path('', AllProfilesView.as_view(), name='all-profiles'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('my-invites/accept/', accept_invitation, name='accept-invite'),
    path('my-invites/reject/', reject_invitation, name='reject-invite'),
    path('<pk>/', ProfileDetailView.as_view(), name='profile-detail-view'),
]

social_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view
from .views import search_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
    path('search/', search_user, name='search-user'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from django.urls import reverse

# Create your models here.

class ProfileManager(models.Manager):
    
    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles

class Profile(models.Model):
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default='No bio...')
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=100, blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProfileManager()

    def get_absolute_url(self):
        return reverse("profiles:profile-detail-view", kwargs={"pk": self.pk})

    def get_friends(self):
        return self.friends.all()

    def get_friends_n(self):
        return self.friends.all().count()

    def get_posts_n(self):
        return self.posts.all().count()

    def get_all_author_posts(self):
        return self.posts.all()

    def get_likes_given_n(self):
        likes = self.like_set.all()
        total_liked = 0 
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked
    
    def get_likes_received_n(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    def __str__(self):
        return f"{self.user.username} - {self.created.strftime('%d-%m-%Y')}"

    
    
        


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)

class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs

class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = RelationshipManager()


    def __str__(self):
        return f"{self.sender} - {self.receiver} - {self.status}"

profiles/forms.py
from django import forms
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'bio', 'avatar',]

profiles/views.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render
from .models import Profile, Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView, DetailView
from django.shortcuts import redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
@login_required
def my_profile_view(request):
    obj = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=obj)
    is_confirmed = False

    if request.method == "POST":
        if form.is_valid():
            is_confirmed = True
            form.save()

    context = {
        'obj': obj,
        'form': form,
        'is_confirmed': is_confirmed
    }
    return render(request, 'profiles/profile.html', context)

@login_required
def my_invites_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitations_received(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True

    context = {
        'qs': results,
        'is_empty': is_empty,
    }

    return render(request, 'profiles/my-invites.html', context)

@login_required
def accept_invitation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:my-invites')

@login_required
def reject_invitation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.get(pk=pk)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:my-invites')


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'profiles/detail.html'

    # def get_object(self):
    #     slug = self.kwargs.get('slug')
    #     profile = Profile.objects.get(slug=slug)
    #     return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['posts'] = self.get_object().get_all_author_posts()
        context['len_posts'] = True if len(self.get_object().get_all_author_posts()) > 0 else False
        return context



class AllProfilesView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/all-profiles.html'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True

        return context

@login_required
def send_invatation(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile')

@login_required
def remove_from_friends(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile')







    

profiles/templates/profiles/all-profiles.html
{% extends 'base.html' %}

{% block title %}
All profiles
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No profiles to interact with</h1>
    {% endif %}

    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="{{obj.get_absolute_url}}"><button class="ui primary button mb-5 w-big">See profile</button></a>
                        <br>

                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'profiles:send-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                            </form>
                         {% endif %}

                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                        {% endif %}

                        {% if request.user in obj.friends.all %}
                        <form action="{% url 'profiles:remove-friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        </form>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

profiles/templates/profiles/detail.html
{% extends 'base.html' %}

{% block title %}
Profile detail
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src={{object.avatar.url}}>
            <h1>{{object.user}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ object.get_posts_n }}</div>
                </div>
                <div class="item">
                    Likes given
                    <div class="ui label">{{ object.get_likes_given_n }}</div>
                </div>
                <div class="item">
                    Likes received
                    <div class="ui label">{{ object.get_likes_received_n }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ object.get_friends_n }}</div>
                </div>
            </div>

            {% if object.user not in rel_receiver and object.user not in rel_sender %}
                <form action="{% url 'profiles:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                </form>
            {% endif %}

            {% if object.user in rel_receiver and request.user not in object.friends.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
            {% endif %}

            {% if request.user in object.friends.all %}
                <form action="{% url 'profiles:remove-friend' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                </form>
            {% endif %}

        </div>
        <div class="twelve wide column">
            {% if len_posts %}
                {% for post in posts %}
                    <div class="segment ui fluid">
                        {{post.content}}
                    </div>
                {% endfor %}
            {% else %}
                <h1>No posts of this user ...</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/my-invites.html
{% extends 'base.html' %}

{% block title %}
My invites
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No invatations here..</h1>
    {% endif %}
 
    {% for obj in qs %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</h3>
                        <br>
                        <a href="{{obj.get_absolute_url}}">
                            <button class="ui primary button w-big mb-5">See profile</button>
                        </a>
                        <form action="{% url 'profiles:accept-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui positive basic button w-big mb-5">
                                <i class="check icon"></i>
                                Accept invite
                            </button>
                        </form>
                         <form action="{% url 'profiles:reject-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button w-big mb-5">
                                <i class="close icon"></i>
                                Reject invite
                            </button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

profiles/templates/profiles/profile.html
{% extends 'base.html' %}

{% block title %}
My profile
{% endblock title %}

{% block content %}

    <!--Profile info-->
    <div class="ui segment">
        {% if is_confirmed %}
            <div class="ui green message">Your profile has been updated</div>
        {% endif %}
        <h1>My profile - {{obj.user}}</h1>
        <p>{{obj.first_name}} {{obj.last_name}}</p>
        <img src="{{obj.avatar.url}}" alt="avatar" class="avatar-sm">
        <p>{{obj.bio}}</p>
        <p>{{obj.country}}</p>
        <h5>Friends</h5>
        <ul>
            {% for friend in obj.get_friends %}
                <li>{{friend}}</li>
            {% endfor %}
        </ul>
        <p>Total friends: {{obj.get_friends_n}}</p>
        <div>
            <p>Number of posts: {{obj.get_posts_n}}</p>
            <p>Number of likes given: {{obj.get_likes_given_n}}</p>
            <p>Number of likes received: {{obj.get_likes_received_n}}</p>

            
        </div>
    </div>

    

    <button class='ui secondary button' id='modal-btn'>Update profile</button>
    
    <!--Modal for upload profile-->
    <div class="ui modal">
        <i class="close icon"></i>
        <div class="header">
            Update Your profile
        </div>
        <div class="image content">
            <div class="ui medium image">
            <img src="{{obj.avatar.url}}" alt="avatar" class="avatar-sm">
            </div>
            <div class="description">
                <div class="ui header">Update your profile my friend</div>
                <form action="" method="POST" class="ui form" enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type='submit' class="ui positive right labeled icon button">
                        Update
                        <i class="checkmark icon"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
  
    
{% endblock content %}