posts/urls.py
from django.urls import path
from .views import main_post_view, liked_unliked_view, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('',main_post_view, name='main-post-view'),
    path('liked/',liked_unliked_view, name='liked-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view, 
    my_invites_view, 
    AllProfilesView,
    send_invatation, 
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    ProfileDetailView,
)

app_name = 'profiles'

urlpatterns = [
    path('my-profile/', my_profile_view, name='my-profile'),
    path('my-invites/', my_invites_view, name='my-invites'),
    path('', AllProfilesView.as_view(), name='all-profiles'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('my-invites/accept/', accept_invitation, name='accept-invite'),
    path('my-invites/reject/', reject_invitation, name='reject-invite'),
    path('<pk>/', ProfileDetailView.as_view(), name='profile-detail-view'),
]

social_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view
from .views import search_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
    path('search/', search_user, name='search-user'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <!--Custom css ADD HERE-->
    <link rel="stylesheet" type='text/css' href="{% static 'style.css' %}">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

  
    <title>Meth - {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="ui container">
      {% block content %}
      {% endblock content %}
    </div>

    {% block scripts %}
    {% endblock scripts %}
   
   <!--Custom js ADD HERE-->
   <script type="text/javascript" src="{% static 'main.js' %}"></script>

  </body>
</html>

templates/navbar.html
{% url 'home' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile' as path_to_my_profile %}
{% url 'profiles:my-invites' as path_to_my_invites %}
{% url 'profiles:all-profiles' as path_to_all_profiles %}
{% url 'search-user' as search %}

<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>Meth</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Board
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="{{search}}" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a user...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>
        
            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                 {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>

templates/searched.html
{% extends 'base.html' %}

{% block title %}
    search results
{% endblock title %}
    
{% block content %}
    {% if is_empty %}
        <h3>No results</h3>
    {% else %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{profile.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{profile.user}}</h3>
                        <p>{{profile.bio}}</p>
                        <a href="{{profile.get_absolute_url}}"><button class="ui primary button mb-5 w-big">See profile</button></a>
                        <br>
                    </div>

                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}